# .goreleaser.yml
# Build customization
---
builds:
  -
    binary: cr
    goarch:
      - amd64
    goos:
      - windows
      - linux
    main: main.go
release:
  github:
    owner: dohq
    name: create_repo
archive:
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  replacements:
    amd64: 64-bit
    386: 32-bit
